target-version = "py312"
line-length = 88

[lint]
select = ["E", "F", "I", "UP"]

[lint.per-file-ignores]
"**/dashboard.py" = ["E501"]
"**/ui/css.py" = ["E501"]
"**/ui/js.py" = ["E501"]
"**/ui/html.py" = ["E501"]
